### ISSUE TITLE
btrfs receive sometimes can not find some internal files

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#371] opened 2021-02-20 09:37 UTC
I sometimes see an error like:

```
ERROR: cannot open /mnt/masa-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134/o223727-162425-0: No such file or directory
```

During my examinations, I found out that this is caused by issuing wrong parent snapshot to `btrfs send`: 

### Failed 

```
sudo btrfs send -p /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210214T0015 /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134 | mbuffer -v 1 | sudo btrfs receive /mnt/masa-root/snapshots/erik3/var/lib/lxc/fc4/
At subvol /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134
At snapshot rootfs.20210220T1134
in @ 28.0 MiB/s, out @ 38.0 MiB/s, 48.0 MiB total, buffer  23% full
ERROR: cannot open /mnt/masa-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134/o223727-162425-0: No such file or directory

summary: 60.0 MiByte in  5.1sec - average of 11.8 MiB/s
```

### Succeeded

```
sudo btrfs send -p /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210213T0356 /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134 | mbuffer -v 1 | sudo btrfs receive /mnt/masa-root/snapshots/erik3/var/lib/lxc/fc4/
At subvol /mnt/heybe-root/snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134
At snapshot rootfs.20210220T1134
in @ 24.0 MiB/s, out @ 24.0 MiB/s,  569 MiB total, buffer   0% full
summary:  571 MiByte in 29.2sec - average of 19.6 MiB/s
```

### Info 

In `/mnt/heybe-root/`: 
```
snapshots/erik3/var/lib/lxc/fc4/rootfs.20210213T0356
	Name: 			rootfs.20210213T0356
	UUID: 			488f5eb5-8ec0-414e-89a6-b28ad85d3005
	Parent UUID: 		7bc2daa5-d6c6-2142-849f-a0c429fa44c2
	Received UUID: 		-
	Creation time: 		2021-02-13 03:56:31 +0300
	Subvolume ID: 		5820
	Generation: 		147362
	Gen at creation: 	147362
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			readonly

snapshots/erik3/var/lib/lxc/fc4/rootfs.20210214T0015
	Name: 			rootfs.20210214T0015
	UUID: 			8df93123-80e1-4149-97d0-e92b5747977b
	Parent UUID: 		7bc2daa5-d6c6-2142-849f-a0c429fa44c2
	Received UUID: 		-
	Creation time: 		2021-02-14 00:15:49 +0300
	Subvolume ID: 		6007
	Generation: 		149486
	Gen at creation: 	149485
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			readonly
	Snapshot(s):

snapshots/erik3/var/lib/lxc/fc4/rootfs.20210220T1134
	Name: 			rootfs.20210220T1134
	UUID: 			0214f146-d691-2b41-87e0-6f7df401e6cc
	Parent UUID: 		229da998-3580-db41-9adb-0d4f47337e5a
	Received UUID: 		-
	Creation time: 		2021-02-20 11:34:39 +0300
	Subvolume ID: 		8115
	Generation: 		164610
	Gen at creation: 	164609
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			readonly
```

# Opinions 

I *think* this is because of a workflow like that: 

```
s1 -> s2 -> s3     s4 -> s5
       \-----------^
```
Sending above snapshots in the order of `s1, s2, s3, s4, s5` creates this kind of conflicts. Maybe not, I don't know.

# Workaround

Whenever `btrbk` fails with that error, I manually try issuing an older parent snapshot manually.

# Suggestion 

`btrbk` should automatically try older snapshots in case of such an error.

**Comment by digint** [comment] 2021-02-26 16:34
Duplicate of #91, #223, #225, #251 : upstream (btrfs) bug.

**Closed by digint** 2021-02-26 16:34 UTC
Labels: duplicate, upstream bug
