### ISSUE TITLE
No UUID found allthough they're there possibly breaking change in btrfs-progs 6.1

### ISSUE THREAD

**Issue by theoware** [digint/btrbk#521] opened 2022-12-30 08:47 UTC
Hi since yesterday I've been getting the error `!!! Aborted: subvolume has no UUID` from Btrbk. The days before it worked fine. After downgrading `btrfs-progs-6.1-1.fc37.x86_64` to `btrfs-progs-6.0-1.fc37.x86_64` the error was fixed. Maybe something broke in between that version change.

This is the output of `btrfs subvolume show /btrfs_pool/root`
>         Name:                   root
>         UUID:                   9b1670d0-cfb1-0244-8655-1a91722c5548
>         Parent UUID:            -
>         Received UUID:          -
>         Creation time:          2022-12-25 06:34:58 +0100
>         Subvolume ID:           257
>         Generation:             4098
>         Gen at creation:        9
>         Parent ID:              5
>         Top level ID:           5
>         Flags:                  -
>         Send transid:           0
>         Send time:              2022-12-25 06:34:58 +0100
>         Receive transid:        0
>         Receive time:           -

**Comment by tdolega** [comment] 2022-12-30 11:11
Duplicate of #519 
Already fixed on Arch with version 6.1-2. Fedora also has an open issue. Not sure about other distros.

**Closed** 2022-12-30 11:28 UTC
Labels: duplicate

**Comment by theoware** [comment] 2022-12-30 12:35
I'm sorry, I searched the repo but didn't find that issue. Thanks!
